[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32G431KBTx --connect-under-reset'
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"